services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - my_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
